name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  DOTNET_PATH: ${{ github.workspace }}/CalculationEngine/CalculationEngine/
  CONFIGURATION: 'Release'  

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@0.9.6
        with:
          versionSpec: '5.x'      
          
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@0.9.6
        
      - name: Get Version
        run: | 
          echo 'NugetVersionV2': ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.DOTNET_PATH }}        
        
      - name: Build
        run: dotnet build ${{ env.DOTNET_PATH }} --no-restore -c ${{ env.CONFIGURATION}}
        
      - name: Test
        run: dotnet test ${{ env.DOTNET_PATH }} --no-build --verbosity normal

      - name: Pack
        run: dotnet pack ${{ env.DOTNET_PATH }}/CalculationEngine.csproj --output ./artifacts -c ${{ env.CONFIGURATION}}  -p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./artifacts/*.nupkg

  deploy:
    needs: build
    if: github.rf =='refs/heads/develop' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Download Artifact
      uses: actions/download-artifact@v1
      with: 
        name: nupkg

    - name: List sources nuget
      run: dotnet nuget list source

    - name: Add package source
      run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -u robertath -p ${{ secrets.NUGETAPIKEY }} --store-password-in-clear-text -n github

    - name: List sources nuget
      run: dotnet nuget list source
        
    - name: Push to GitHub package registry
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source github --skip-duplicate --no-symbols   
