name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  DOTNET_PATH: ${{ github.workspace }}'/CalculationEngine/CalculationEngine/'
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.DOTNET_PATH }}        
      
    - name: Build
      run: dotnet build ${{ env.DOTNET_PATH }} --no-restore -c ${{ env.CONFIGURATION}}
      
    - name: Test
      run: dotnet test ${{ env.DOTNET_PATH }} --no-build --verbosity normal

    - name: Pack
      run: dotnet pack ${{ env.DOTNET_PATH }}/CalculationEngine.csproj --output ./artifacts -c ${{ env.CONFIGURATION}} -p:Version=$GITHUB_RUN_ID

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./artifacts/*.nupkg

  publish:
    needs: build
    if: github.rf =='refs/heads/develop' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v1
      with: 
        name: nupkg
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Add package source
      run: dotnet nuget add source https://nuget.pkg.github.com/robertath/index.json -n github -u robertath =p ${{ secrets.NUGETAPIKEY }} --store-password-in-clear-text

    - name: Publish
      run: dotnet nuget push ./nupkg/**.nupkg --source github --api-key ${{ secrets.NUGETAPIKEY }}



    
